run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
    - format: json
      path: ./golangci-report.json

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - gosimple
    - misspell
    - unparam

issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - unparam
        - unused
    - linters:
        - staticcheck
      text: "SA1029"

severity:
  default-severity: error
  rules:
    - linters:
        - govet
      severity: error
