// Package sqlc provides database query interfaces (generated by sqlc).
package sqlc

// Queries interface for database operations
type Queries struct{}

// New creates a new Queries instance
func New() *Queries {
	return &Queries{}
}

// NewQueries creates a new Queries instance from a querier
func NewQueries(querier interface{}) *Queries {
	return &Queries{}
}

// ModelEndpoint represents an endpoint model
type ModelEndpoint struct {
	ID       string
	Provider string
	Model    string
}

// ProviderAccount represents a provider account
type ProviderAccount struct {
	ID       string
	Provider string
	Account  string
}

// ProviderAccountLimit represents rate limits for a provider account
type ProviderAccountLimit struct {
	ID          string
	AccountID   string
	Limit       int64
	ResetAt     int64
}
